name: My workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_SECRET: ${{ secrets.ACCESS_KEY}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run your JavaScript code
        run: node app.js
